package com.laker.postman.snippet;

public enum Category {
    // 基础分类
    PRE_SCRIPT, ASSERT, EXTRACT, LOCAL_VAR, ENV_VAR, ENCODE,
    ENCRYPT, STRING, ARRAY, JSON, DATE, REGEX, LOG, CONTROL, TOKEN, COOKIES, OTHER,
    // 内置库分类
    CRYPTOJS, LODASH, MOMENT, EXAMPLES,
    // 高级场景分类
    AUTHENTICATION, PERFORMANCE, VALIDATION, DATA_PROCESSING, REQUEST_MODIFICATION
}
