package com.laker.postman.snippet;

public enum SnippetType {
    // Pre-script category
    SET_REQUEST_VARIABLE(Category.PRE_SCRIPT, "snippet.setRequestVariable.title", "snippet.setRequestVariable.desc", "pm.variables.set('requestId', pm.uuid());\nconsole.log('Generated request ID: ' + pm.variables.get('requestId'));"),
    SET_LOCAL_VARIABLE(Category.PRE_SCRIPT, "snippet.setLocalVariable.title", "snippet.setLocalVariable.desc", "pm.variables.set('tempKey', 'tempValue');\nconsole.log('Set execution variable: ' + pm.variables.get('tempKey'));"),
    RANDOM_UUID(Category.PRE_SCRIPT, "snippet.randomUUID.title", "snippet.randomUUID.desc", "pm.environment.set('uuid', pm.uuid());\nconsole.log('Generated random UUID: ' + pm.environment.get('uuid'));"),
    DYNAMIC_TIMESTAMP(Category.PRE_SCRIPT, "snippet.dynamicTimestamp.title", "snippet.dynamicTimestamp.desc", "pm.environment.set('timestamp', pm.getTimestamp());\nconsole.log('Generated timestamp: ' + pm.environment.get('timestamp'));"),
    SIGNATURE(Category.PRE_SCRIPT, "snippet.signature.title", "snippet.signature.desc", "// Assume signature needs to be generated\nvar timestamp = Date.now();\nvar appKey = pm.environment.get('appKey');\nvar appSecret = pm.environment.get('appSecret');\n\n// Build string to sign\nvar stringToSign = 'appKey=' + appKey + '&timestamp=' + timestamp;\n\n// Calculate signature (using SHA256)\nvar signature = SHA256(stringToSign + appSecret).toString();\n\n// Set to environment variable\npm.environment.set('timestamp', timestamp);\npm.environment.set('signature', signature);\n\nconsole.log('Generated signature: ' + signature);"),
    DYNAMIC_PARAM(Category.PRE_SCRIPT, "snippet.dynamicParam.title", "snippet.dynamicParam.desc", "// Get current date\nvar now = new Date();\n\n// Format as YYYY-MM-DD\nvar date = now.getFullYear() + '-' + \n    ('0' + (now.getMonth() + 1)).slice(-2) + '-' + \n    ('0' + now.getDate()).slice(-2);\n\n// Save to environment variable\npm.environment.set('currentDate', date);\nconsole.log('Current date: ' + date);"),
    JWT_PARSE(Category.PRE_SCRIPT, "snippet.jwtParse.title", "snippet.jwtParse.desc", "// Parse JWT Token\nvar token = pm.environment.get('jwt_token');\nif (token) {\n    // Split Token\n    var parts = token.split('.');\n    if (parts.length === 3) {\n        // Decode payload part (base64)\n        var payload = JSON.parse(atob(parts[1]));\n        console.log('Token parse result:', payload);\n        // Extract specific field\n        if (payload.exp) {\n            console.log('Token expiration:', new Date(payload.exp * 1000));\n        }\n    }\n}"),
    ENCRYPT_REQUEST_DATA(Category.PRE_SCRIPT, "snippet.encryptRequestData.title", "snippet.encryptRequestData.desc", "// Read and update a Postman raw RequestBody\nif (pm.request.body && pm.request.body.mode === 'raw') {\n    var requestData = JSON.parse(pm.request.body.raw || '{}');\n\n    if (requestData.password) {\n        requestData.password = CryptoJS.MD5(requestData.password).toString();\n        pm.request.body.update(JSON.stringify(requestData));\n        console.log('Password encrypted and request body updated');\n    }\n}"),
    DYNAMIC_HEADER(Category.PRE_SCRIPT, "snippet.dynamicHeader.title", "snippet.dynamicHeader.desc", "// Set dynamic request headers like timestamp and signature\nvar timestamp = Date.now();\nvar nonce = Math.random().toString(36).substring(2, 15);\n\n// Set to environment variable for use in headers\npm.environment.set('req_timestamp', timestamp);\npm.environment.set('req_nonce', nonce);\n\nconsole.log('Set request timestamp: ' + timestamp);\nconsole.log('Set request nonce: ' + nonce);"),
    CONDITIONAL(Category.PRE_SCRIPT, "snippet.conditional.title", "snippet.conditional.desc", "// Use different parameters based on environment\nvar env = pm.environment.get('environment');\n\nif (env === 'production') {\n    pm.environment.set('base_url', 'https://api.example.com');\n    console.log('Switched to production environment');\n} else if (env === 'staging') {\n    pm.environment.set('base_url', 'https://staging-api.example.com');\n    console.log('Switched to staging environment');\n} else {\n    pm.environment.set('base_url', 'https://dev-api.example.com');\n    console.log('Switched to development environment');\n}"),
    DYNAMIC_MODIFY_HEADER(Category.PRE_SCRIPT, "snippet.dynamicModifyHeader.title", "snippet.dynamicModifyHeader.desc", "// Get and modify request headers\nif (pm.request && pm.request.headers) {\n    // Add custom request header\n    pm.request.headers.add({\n        key: 'X-Custom-Header',\n        value: 'Custom-Value-' + Date.now()\n    });\n    \n    // Add authentication info\n    pm.request.headers.add({\n        key: 'Authorization',\n        value: 'Bearer ' + pm.environment.get('token')\n    });\n    \n    console.log('Dynamically added request headers');\n}\n"),
    DYNAMIC_MODIFY_BODY(Category.PRE_SCRIPT, "snippet.dynamicModifyBody.title", "snippet.dynamicModifyBody.desc", "// Use the Postman RequestBody collections for the active body mode\nif (pm.request.body && pm.request.body.mode === 'formdata') {\n    pm.request.body.formdata.add({key: 'extraField', value: 'extraValue', type: 'text'});\n}\nif (pm.request.body && pm.request.body.mode === 'urlencoded') {\n    pm.request.body.urlencoded.add({key: 'token', value: pm.environment.get('token')});\n}\nif (pm.request.body && pm.request.body.mode === 'raw') {\n    pm.request.body.update(pm.request.body.raw + '\\n');\n}"),
    DYNAMIC_MODIFY_PARAM(Category.PRE_SCRIPT, "snippet.dynamicModifyParam.title", "snippet.dynamicModifyParam.desc", "// Add a query parameter through Postman's Url query list\npm.request.url.query.add({key: 'timestamp', value: Date.now().toString()});"),
    SEND_HTTP_REQUEST(Category.PRE_SCRIPT, "snippet.sendHttpRequest.title", "snippet.sendHttpRequest.desc", "// 前置脚本里发送一个可直接测试的 HTTP 请求\npm.sendRequest({\n    url: 'https://httpbin.org/get?source=easy-postman&from=pre-script',\n    method: 'GET',\n    header: {\n        'X-Debug-Token': pm.environment.get('debugToken') || 'demo-token'\n    }\n}, function (err, response) {\n    if (err) {\n        console.error('请求失败:', err.message);\n        return;\n    }\n\n    pm.test('httpbin 请求返回 200', function () {\n        pm.expect(response.code).to.equal(200);\n    });\n\n    var data = response.json();\n    pm.environment.set('lastHttpbinUrl', data.url || '');\n    pm.environment.set('lastHttpbinSource', data.args && data.args.source ? data.args.source : '');\n\n    console.log('响应状态:', response.code, response.status);\n    console.log('httpbin url:', data.url);\n    console.log('httpbin args:', JSON.stringify(data.args));\n});"),
    ITERATION_DATA_USAGE(Category.PRE_SCRIPT, "snippet.iterationDataUsage.title", "snippet.iterationDataUsage.desc", "// CSV / JSON 数据驱动示例\n// 请求 URL、Header、Body 里可以直接使用 {{userId}}、{{token}} 这样的占位符\n// 脚本里使用 pm.iterationData.get('列名') 只读当前行数据\n\nvar userId = pm.iterationData.get('userId');\nvar token = pm.iterationData.get('token');\n\npm.test('当前迭代数据存在', function () {\n    pm.expect(userId).to.not.eql(null);\n});\n\npm.variables.set('currentUserId', userId || '');\npm.variables.set('currentToken', token || '');\n\nconsole.log('iteration userId =', userId);\nconsole.log('request placeholder example: {{userId}}');"),

    // Assertion category
    ASSERT_STATUS_200(Category.ASSERT, "snippet.assertStatus200.title", "snippet.assertStatus200.desc", "pm.test('Status code is 200', function () {\n    pm.response.to.have.status(200);\n});"),
    ASSERT_BODY_CONTAINS(Category.ASSERT, "snippet.assertBodyContains.title", "snippet.assertBodyContains.desc", "pm.test('Body contains string', function () {\n    pm.expect(pm.response.text()).to.include('success');\n});"),
    ASSERT_JSON_VALUE(Category.ASSERT, "snippet.assertJsonValue.title", "snippet.assertJsonValue.desc", "pm.test('JSON value check', function () {\n    var jsonData = pm.response.json();\n    pm.expect(jsonData.code).to.eql(0);\n});"),
    ASSERT_HEADER_PRESENT(Category.ASSERT, "snippet.assertHeaderPresent.title", "snippet.assertHeaderPresent.desc", "pm.test('Header is present', function () {\n    pm.response.to.have.header('Content-Type');\n});"),
    ASSERT_RESPONSE_TIME(Category.ASSERT, "snippet.assertResponseTime.title", "snippet.assertResponseTime.desc", "pm.test('Response time is less than 1000ms', function () {\n    pm.expect(pm.response.responseTime).to.be.below(1000);\n});"),
    ASSERT_FIELD_EXISTS(Category.ASSERT, "snippet.assertFieldExists.title", "snippet.assertFieldExists.desc", "pm.test('Field exists', function () {\n    var jsonData = pm.response.json();\n    pm.expect(jsonData).to.have.property('data');\n});"),
    ASSERT_ARRAY_LENGTH(Category.ASSERT, "snippet.assertArrayLength.title", "snippet.assertArrayLength.desc", "pm.test('Array length is 3', function () {\n    var arr = pm.response.json().list;\n    pm.expect(arr.length).to.eql(3);\n});"),
    ASSERT_REGEX(Category.ASSERT, "snippet.assertRegex.title", "snippet.assertRegex.desc", "pm.test('Body regex match', function () {\n    pm.expect(pm.response.text()).to.match(/success/);\n});"),
    ASSERT_STATUS_SUCCESS(Category.ASSERT, "snippet.assertStatusSuccess.title", "snippet.assertStatusSuccess.desc", "pm.test('Status code is in 2xx range', function () {\n    pm.expect(pm.response.code).to.be.within(200, 299);\n});"),
    ASSERT_CONTENT_TYPE(Category.ASSERT, "snippet.assertContentType.title", "snippet.assertContentType.desc", "pm.test('Content-Type is application/json', function () {\n    pm.expect(pm.response.headers.get('Content-Type')).to.include('application/json');\n});"),
    ASSERT_BODY_NOT_EMPTY(Category.ASSERT, "snippet.assertBodyNotEmpty.title", "snippet.assertBodyNotEmpty.desc", "pm.test('Response body is not empty', function () {\n    pm.expect(pm.response.text()).to.not.be.empty;\n});"),
    ASSERT_JSON_SCHEMA(Category.ASSERT, "snippet.assertJsonSchema.title", "snippet.assertJsonSchema.desc", "pm.test('Response matches JSON schema', function () {\n    var schema = {\n        type: 'object',\n        required: ['code', 'data'],\n        properties: {\n            code: { type: 'number' },\n            data: { type: 'object' }\n        }\n    };\n    var jsonData = pm.response.json();\n    pm.expect(jsonData).to.have.jsonSchema(schema);\n});"),
    ASSERT_RESPONSE_SIZE(Category.ASSERT, "snippet.assertResponseSize.title", "snippet.assertResponseSize.desc", "pm.test('Response size is acceptable', function () {\n    pm.expect(pm.response.text().length).to.be.below(10000);\n});"),
    ASSERT_JSON_IS_ARRAY(Category.ASSERT, "snippet.assertJsonIsArray.title", "snippet.assertJsonIsArray.desc", "pm.test('Response data is an array', function () {\n    var jsonData = pm.response.json();\n    pm.expect(jsonData).to.be.an('array');\n});"),
    ASSERT_JSON_NOT_EMPTY_ARRAY(Category.ASSERT, "snippet.assertJsonNotEmptyArray.title", "snippet.assertJsonNotEmptyArray.desc", "pm.test('Response array is not empty', function () {\n    var jsonData = pm.response.json();\n    pm.expect(jsonData).to.be.an('array').that.is.not.empty;\n});"),
    ASSERT_MULTIPLE_CONDITIONS(Category.ASSERT, "snippet.assertMultipleConditions.title", "snippet.assertMultipleConditions.desc", "pm.test('Multiple assertions', function () {\n    var jsonData = pm.response.json();\n    pm.expect(pm.response.code).to.equal(200);\n    pm.expect(jsonData).to.have.property('success', true);\n    pm.expect(jsonData.data).to.be.an('object');\n    pm.expect(pm.response.responseTime).to.be.below(1000);\n});"),

    // Extraction category
    EXTRACT_JSON_TO_ENV(Category.EXTRACT, "snippet.extractJsonToEnv.title", "snippet.extractJsonToEnv.desc", "var jsonData = pm.response.json();\npm.environment.set('token', jsonData.token);"),
    EXTRACT_HEADER_TO_ENV(Category.EXTRACT, "snippet.extractHeaderToEnv.title", "snippet.extractHeaderToEnv.desc", "var token = pm.response.headers.get('X-Token');\npm.environment.set('token', token);"),
    EXTRACT_REGEX_TO_ENV(Category.EXTRACT, "snippet.extractRegexToEnv.title", "snippet.extractRegexToEnv.desc", "var match = pm.response.text().match(/token=(\\w+)/);\nif (match) {\n    pm.environment.set('token', match[1]);\n}"),
    EXTRACT_NESTED_JSON(Category.EXTRACT, "snippet.extractNestedJson.title", "snippet.extractNestedJson.desc", "var jsonData = pm.response.json();\n// Extract nested data\nif (jsonData.data && jsonData.data.user) {\n    pm.environment.set('userId', jsonData.data.user.id);\n    pm.environment.set('userName', jsonData.data.user.name);\n    console.log('Extracted user info: ' + jsonData.data.user.name);\n}"),
    EXTRACT_ARRAY_ELEMENT(Category.EXTRACT, "snippet.extractArrayElement.title", "snippet.extractArrayElement.desc", "var jsonData = pm.response.json();\n// Extract first element from array\nif (jsonData.list && jsonData.list.length > 0) {\n    var firstItem = jsonData.list[0];\n    pm.environment.set('firstItemId', firstItem.id);\n    console.log('First item ID:', firstItem.id);\n}"),
    EXTRACT_MULTIPLE_VALUES(Category.EXTRACT, "snippet.extractMultipleValues.title", "snippet.extractMultipleValues.desc", "var jsonData = pm.response.json();\n// Batch extract multiple values\npm.environment.set('token', jsonData.token || '');\npm.environment.set('refreshToken', jsonData.refreshToken || '');\npm.environment.set('expiresIn', jsonData.expiresIn || '');\npm.environment.set('userId', jsonData.userId || '');\nconsole.log('Batch extracted authentication info');"),
    EXTRACT_ALL_IDS(Category.EXTRACT, "snippet.extractAllIds.title", "snippet.extractAllIds.desc", "var jsonData = pm.response.json();\n// Extract all IDs from array\nif (jsonData.list && Array.isArray(jsonData.list)) {\n    var ids = jsonData.list.map(function(item) {\n        return item.id;\n    });\n    pm.environment.set('allIds', JSON.stringify(ids));\n    console.log('Extracted IDs:', ids);\n}"),
    EXTRACT_WITH_DEFAULT(Category.EXTRACT, "snippet.extractWithDefault.title", "snippet.extractWithDefault.desc", "var jsonData = pm.response.json();\n// Extract with default value\nvar token = jsonData.token || 'default_token';\nvar userId = jsonData.userId || '0';\npm.environment.set('token', token);\npm.environment.set('userId', userId);\nconsole.log('Token:', token, 'UserId:', userId);"),

    // Local variable management
    LOCAL_SET(Category.LOCAL_VAR, "snippet.localSet.title", "snippet.localSet.desc", "pm.variables.set('key', 'value');\nconsole.log('Set execution variable: ' + pm.variables.get('key'));"),
    LOCAL_GET(Category.LOCAL_VAR, "snippet.localGet.title", "snippet.localGet.desc", "var value = pm.variables.get('key');\nconsole.log('Execution variable value: ' + value);"),
    LOCAL_HAS(Category.LOCAL_VAR, "snippet.localHas.title", "snippet.localHas.desc", "if (pm.variables.has('key')) {\n    console.log('Execution variable exists');\n} else {\n    console.log('Execution variable does not exist');\n}"),
    LOCAL_UNSET(Category.LOCAL_VAR, "snippet.localUnset.title", "snippet.localUnset.desc", "pm.variables.unset('key');\nconsole.log('Deleted execution variable: key');"),
    LOCAL_CLEAR(Category.LOCAL_VAR, "snippet.localClear.title", "snippet.localClear.desc", "pm.variables.clear();\nconsole.log('Cleared all execution variables');"),
    LOCAL_BATCH_SET(Category.LOCAL_VAR, "snippet.localBatchSet.title", "snippet.localBatchSet.desc", "var data = {\n    'userId': '12345',\n    'sessionId': pm.uuid(),\n    'timestamp': Date.now()\n};\n\nObject.keys(data).forEach(function(key) {\n    pm.variables.set(key, data[key]);\n});\n\nconsole.log('Batch set execution variables');"),
    LOCAL_FOREACH(Category.LOCAL_VAR, "snippet.localForeach.title", "snippet.localForeach.desc", "// Note: pm.variables itself does not provide traversal method\n// Here demonstrates traversal with a known variable name list\nvar knownKeys = ['userId', 'sessionId', 'timestamp'];\n\nknownKeys.forEach(function(key) {\n    if (pm.variables.has(key)) {\n        console.log(key + ': ' + pm.variables.get(key));\n    }\n});"),
    LOCAL_CONDITIONAL_SET(Category.LOCAL_VAR, "snippet.localConditionalSet.title", "snippet.localConditionalSet.desc", "// Set execution variable based on condition\nvar userRole = pm.environment.get('userRole');\n\nif (userRole === 'admin') {\n    pm.variables.set('permissions', 'all');\n} else if (userRole === 'user') {\n    pm.variables.set('permissions', 'read');\n} else {\n    pm.variables.set('permissions', 'none');\n}\n\nconsole.log('Set permissions based on user role: ' + pm.variables.get('permissions'));"),
    LOCAL_DEFAULT(Category.LOCAL_VAR, "snippet.localDefault.title", "snippet.localDefault.desc", "// Get execution variable, use default if not exists\nvar userId = pm.variables.get('userId') || 'defaultUser';\nvar timeout = pm.variables.get('timeout') || '5000';\n\nconsole.log('User ID: ' + userId);\nconsole.log('Timeout: ' + timeout);"),

    // Environment variable management
    ENV_SET(Category.ENV_VAR, "snippet.envSet.title", "snippet.envSet.desc", "pm.environment.set('key', 'value');"),
    ENV_GET(Category.ENV_VAR, "snippet.envGet.title", "snippet.envGet.desc", "pm.environment.get('key');"),
    ENV_UNSET(Category.ENV_VAR, "snippet.envUnset.title", "snippet.envUnset.desc", "pm.environment.unset('key');"),
    ENV_CLEAR(Category.ENV_VAR, "snippet.envClear.title", "snippet.envClear.desc", "pm.environment.clear();"),

    // Other operations
    FOREACH_ARRAY(Category.OTHER, "snippet.foreachArray.title", "snippet.foreachArray.desc", "var arr = pm.response.json().list;\narr.forEach(function(item) {\n    // Process each item\n});"),
    IF_ELSE(Category.OTHER, "snippet.ifElse.title", "snippet.ifElse.desc", "if (pm.response.code === 200) {\n    // Success logic\n} else {\n    // Failure logic\n}"),
    PRINT_LOG(Category.OTHER, "snippet.printLog.title", "snippet.printLog.desc", "console.log('Log content');"),
    TRY_CATCH(Category.OTHER, "snippet.tryCatch.title", "snippet.tryCatch.desc", "try {\n    var jsonData = pm.response.json();\n    pm.environment.set('data', jsonData.result);\n    console.log('Data extracted successfully');\n} catch (e) {\n    console.log('Error parsing response:', e.message);\n    pm.environment.set('data', '');\n}"),
    SKIP_REQUEST(Category.OTHER, "snippet.skipRequest.title", "snippet.skipRequest.desc", "// Skip current request based on condition\nvar shouldSkip = pm.environment.get('skipNextRequest');\nif (shouldSkip === 'true') {\n    console.log('Skipping this request');\n    // Note: Cannot actually skip in pre-script, but can set flag\n    pm.environment.set('skipNextRequest', 'false');\n}"),
    DELAY_EXECUTION(Category.OTHER, "snippet.delayExecution.title", "snippet.delayExecution.desc", "// Note: JavaScript setTimeout not fully supported in Postman sandbox\n// Use pm.sendRequest for delayed requests instead\nconsole.log('Request will be sent immediately');\nconsole.log('For delays, use Collection Runner with delay settings');"),
    RANDOM_STRING(Category.OTHER, "snippet.randomString.title", "snippet.randomString.desc", "// Generate random string\nvar randomStr = Math.random().toString(36).substring(2, 15) + \n                Math.random().toString(36).substring(2, 15);\npm.environment.set('randomString', randomStr);\nconsole.log('Random string:', randomStr);"),
    RANDOM_NUMBER(Category.OTHER, "snippet.randomNumber.title", "snippet.randomNumber.desc", "// Generate random number in range\nvar min = 1;\nvar max = 1000;\nvar randomNum = Math.floor(Math.random() * (max - min + 1)) + min;\npm.environment.set('randomNumber', randomNum);\nconsole.log('Random number:', randomNum);"),
    BASIC_AUTH_HEADER(Category.OTHER, "snippet.basicAuthHeader.title", "snippet.basicAuthHeader.desc", "// Generate Basic Auth header\nvar username = pm.environment.get('username');\nvar password = pm.environment.get('password');\nvar credentials = username + ':' + password;\nvar encodedCredentials = btoa(credentials);\npm.request.headers.add({\n    key: 'Authorization',\n    value: 'Basic ' + encodedCredentials\n});\nconsole.log('Basic Auth header added');"),
    BEARER_TOKEN_HEADER(Category.OTHER, "snippet.bearerTokenHeader.title", "snippet.bearerTokenHeader.desc", "// Add Bearer token to Authorization header\nvar token = pm.environment.get('access_token');\nif (token) {\n    pm.request.headers.add({\n        key: 'Authorization',\n        value: 'Bearer ' + token\n    });\n    console.log('Bearer token added to header');\n} else {\n    console.log('No access token found');\n}"),
    HMAC_SIGNATURE(Category.OTHER, "snippet.hmacSignature.title", "snippet.hmacSignature.desc", "// Generate HMAC-SHA256 signature\nvar message = pm.request.url + pm.request.method + pm.getTimestamp();\nvar secret = pm.environment.get('api_secret');\n// Note: HMAC requires crypto library support\nvar signature = SHA256(message + secret).toString();\npm.environment.set('signature', signature);\npm.request.headers.add({\n    key: 'X-Signature',\n    value: signature\n});\nconsole.log('HMAC signature generated');"),
    CHECK_RESPONSE_SUCCESS(Category.OTHER, "snippet.checkResponseSuccess.title", "snippet.checkResponseSuccess.desc", "// Check if response indicates success\nvar jsonData = pm.response.json();\nvar isSuccess = jsonData.success || jsonData.code === 0 || jsonData.status === 'ok';\n\nif (isSuccess) {\n    console.log('Request successful');\n    // Continue with data extraction\n    pm.environment.set('lastRequestSuccess', 'true');\n} else {\n    console.log('Request failed:', jsonData.message || jsonData.error);\n    pm.environment.set('lastRequestSuccess', 'false');\n}"),
    CHAIN_REQUEST_DATA(Category.OTHER, "snippet.chainRequestData.title", "snippet.chainRequestData.desc", "// Prepare data for next request in workflow\nvar jsonData = pm.response.json();\n\n// Extract data for next request\npm.environment.set('nextRequestId', jsonData.nextId);\npm.environment.set('nextRequestToken', jsonData.token);\npm.environment.set('pageNumber', (parseInt(pm.environment.get('pageNumber') || '1') + 1).toString());\n\nconsole.log('Data prepared for next request');\nconsole.log('Next ID:', jsonData.nextId);\nconsole.log('Page:', pm.environment.get('pageNumber'));"),

    // Basic encode/decode functions
    BASE64_ENCODE(Category.ENCODE, "snippet.base64Encode.title", "snippet.base64Encode.desc", "var encoded = btoa('Hello World');\nconsole.log(encoded); // SGVsbG8gV29ybGQ="),
    BASE64_DECODE(Category.ENCODE, "snippet.base64Decode.title", "snippet.base64Decode.desc", "var decoded = atob('SGVsbG8gV29ybGQ=');\nconsole.log(decoded); // Hello World"),
    URL_ENCODE(Category.ENCODE, "snippet.urlEncode.title", "snippet.urlEncode.desc", "var encoded = encodeURIComponent('Hello World!');\nconsole.log(encoded); // Hello%20World%21"),
    URL_DECODE(Category.ENCODE, "snippet.urlDecode.title", "snippet.urlDecode.desc", "var decoded = decodeURIComponent('Hello%20World%21');\nconsole.log(decoded); // Hello World!"),

    // Common string operations
    STR_SUBSTRING(Category.STRING, "snippet.strSubstring.title", "snippet.strSubstring.desc", "var str = 'Hello World';\nvar sub = str.substring(0, 5);\nconsole.log(sub); // Hello"),
    STR_REPLACE(Category.STRING, "snippet.strReplace.title", "snippet.strReplace.desc", "var str = 'Hello World';\nvar newStr = str.replace('World', 'JavaScript');\nconsole.log(newStr); // Hello JavaScript"),
    STR_SPLIT(Category.STRING, "snippet.strSplit.title", "snippet.strSplit.desc", "var str = 'a,b,c,d';\nvar arr = str.split(',');\nconsole.log(arr); // ['a', 'b', 'c', 'd']"),
    STR_TRIM(Category.STRING, "snippet.strTrim.title", "snippet.strTrim.desc", "var str = '  Hello World  ';\nvar trimmed = str.trim();\nconsole.log(trimmed); // 'Hello World'"),
    STR_UPPER_LOWER(Category.STRING, "snippet.strUpperLower.title", "snippet.strUpperLower.desc", "var str = 'Hello World';\nvar upper = str.toUpperCase();\nvar lower = str.toLowerCase();\nconsole.log(upper); // 'HELLO WORLD'\nconsole.log(lower); // 'hello world'"),
    STR_CONCAT(Category.STRING, "snippet.strConcat.title", "snippet.strConcat.desc", "var str1 = 'Hello';\nvar str2 = 'World';\nvar result = str1 + ' ' + str2;\nconsole.log(result); // 'Hello World'\n// Or use concat\nvar result2 = str1.concat(' ', str2);\nconsole.log(result2);"),
    STR_INCLUDES(Category.STRING, "snippet.strIncludes.title", "snippet.strIncludes.desc", "var str = 'Hello World';\nvar hasHello = str.includes('Hello');\nvar hasTest = str.includes('Test');\nconsole.log(hasHello); // true\nconsole.log(hasTest); // false"),
    STR_STARTS_ENDS_WITH(Category.STRING, "snippet.strStartsEndsWith.title", "snippet.strStartsEndsWith.desc", "var str = 'Hello World';\nvar startsWithHello = str.startsWith('Hello');\nvar endsWithWorld = str.endsWith('World');\nconsole.log(startsWithHello); // true\nconsole.log(endsWithWorld); // true"),
    STR_PAD(Category.STRING, "snippet.strPad.title", "snippet.strPad.desc", "var str = '5';\n// Pad start with zeros\nvar padded = str.padStart(3, '0');\nconsole.log(padded); // '005'\n// Pad end\nvar paddedEnd = str.padEnd(3, '0');\nconsole.log(paddedEnd); // '500'"),

    // Date/time handling
    GET_TIMESTAMP(Category.DATE, "snippet.getTimestamp.title", "snippet.getTimestamp.desc", "var timestamp = Date.now();\nconsole.log(timestamp); // Millisecond timestamp"),
    FORMAT_DATE(Category.DATE, "snippet.formatDate.title", "snippet.formatDate.desc", "var date = new Date();\nvar formatted = date.toISOString();\nconsole.log(formatted); // e.g.: 2023-01-01T12:00:00.000Z"),
    FORMAT_DATE_CUSTOM(Category.DATE, "snippet.formatDateCustom.title", "snippet.formatDateCustom.desc", "// Format date as YYYY-MM-DD HH:mm:ss\nvar now = new Date();\nvar formatted = now.getFullYear() + '-' +\n    ('0' + (now.getMonth() + 1)).slice(-2) + '-' +\n    ('0' + now.getDate()).slice(-2) + ' ' +\n    ('0' + now.getHours()).slice(-2) + ':' +\n    ('0' + now.getMinutes()).slice(-2) + ':' +\n    ('0' + now.getSeconds()).slice(-2);\npm.environment.set('formattedDate', formatted);\nconsole.log(formatted);"),
    DATE_ADD_DAYS(Category.DATE, "snippet.dateAddDays.title", "snippet.dateAddDays.desc", "// Add days to current date\nvar now = new Date();\nvar daysToAdd = 7;\nvar futureDate = new Date(now.getTime() + (daysToAdd * 24 * 60 * 60 * 1000));\nvar formatted = futureDate.toISOString().split('T')[0];\npm.environment.set('futureDate', formatted);\nconsole.log('Date after ' + daysToAdd + ' days:', formatted);"),
    UNIX_TIMESTAMP(Category.DATE, "snippet.unixTimestamp.title", "snippet.unixTimestamp.desc", "// Get Unix timestamp (seconds)\nvar unixTimestamp = Math.floor(Date.now() / 1000);\npm.environment.set('unixTimestamp', unixTimestamp);\nconsole.log('Unix timestamp:', unixTimestamp);"),
    PARSE_DATE_STRING(Category.DATE, "snippet.parseDateString.title", "snippet.parseDateString.desc", "// Parse date string\nvar dateString = '2025-01-15T10:30:00Z';\nvar date = new Date(dateString);\nvar timestamp = date.getTime();\nconsole.log('Parsed timestamp:', timestamp);\nconsole.log('Date:', date.toLocaleString());"),
    DATE_DIFF(Category.DATE, "snippet.dateDiff.title", "snippet.dateDiff.desc", "// Calculate difference between dates\nvar startDate = new Date('2025-01-01');\nvar endDate = new Date('2025-01-15');\nvar diffTime = Math.abs(endDate - startDate);\nvar diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));\nconsole.log('Days difference:', diffDays);"),

    // JSON handling
    JSON_TO_OBJ(Category.JSON, "snippet.jsonToObj.title", "snippet.jsonToObj.desc", "var jsonString = '{\"name\":\"test\",\"value\":123}';\nvar obj = JSON.parse(jsonString);\nconsole.log(obj.name); // test"),
    OBJ_TO_JSON(Category.JSON, "snippet.objToJson.title", "snippet.objToJson.desc", "var obj = {name: 'test', value: 123};\nvar jsonString = JSON.stringify(obj);\nconsole.log(jsonString); // {\"name\":\"test\",\"value\":123}"),
    JSON_PRETTY_PRINT(Category.JSON, "snippet.jsonPrettyPrint.title", "snippet.jsonPrettyPrint.desc", "// Format JSON with indentation\nvar obj = {name: 'test', value: 123, nested: {key: 'value'}};\nvar prettyJson = JSON.stringify(obj, null, 2);\nconsole.log(prettyJson);"),
    JSON_DEEP_COPY(Category.JSON, "snippet.jsonDeepCopy.title", "snippet.jsonDeepCopy.desc", "// Deep copy object using JSON\nvar original = {name: 'test', data: {id: 1}};\nvar copy = JSON.parse(JSON.stringify(original));\ncopy.data.id = 2;\nconsole.log('Original:', original.data.id); // 1\nconsole.log('Copy:', copy.data.id); // 2"),
    JSON_MERGE(Category.JSON, "snippet.jsonMerge.title", "snippet.jsonMerge.desc", "// Merge two objects\nvar obj1 = {name: 'test', value: 1};\nvar obj2 = {value: 2, extra: 'data'};\nvar merged = Object.assign({}, obj1, obj2);\nconsole.log(merged); // {name: 'test', value: 2, extra: 'data'}"),
    JSON_FILTER_KEYS(Category.JSON, "snippet.jsonFilterKeys.title", "snippet.jsonFilterKeys.desc", "// Extract specific keys from object\nvar data = {id: 1, name: 'test', value: 100, extra: 'ignore'};\nvar allowedKeys = ['id', 'name', 'value'];\nvar filtered = {};\nallowedKeys.forEach(function(key) {\n    if (data.hasOwnProperty(key)) {\n        filtered[key] = data[key];\n    }\n});\nconsole.log('Filtered:', filtered);"),

    // Array operations
    ARRAY_FILTER(Category.ARRAY, "snippet.arrayFilter.title", "snippet.arrayFilter.desc", "var arr = [1, 2, 3, 4, 5];\nvar filtered = arr.filter(function(item) {\n    return item > 3;\n});\nconsole.log(filtered); // [4, 5]"),
    ARRAY_MAP(Category.ARRAY, "snippet.arrayMap.title", "snippet.arrayMap.desc", "var arr = [1, 2, 3];\nvar mapped = arr.map(function(item) {\n    return item * 2;\n});\nconsole.log(mapped); // [2, 4, 6]"),
    ARRAY_FIND(Category.ARRAY, "snippet.arrayFind.title", "snippet.arrayFind.desc", "var arr = [{id: 1, name: 'A'}, {id: 2, name: 'B'}];\nvar found = arr.find(function(item) {\n    return item.id === 2;\n});\nconsole.log(found); // {id: 2, name: 'B'}"),
    ARRAY_REDUCE(Category.ARRAY, "snippet.arrayReduce.title", "snippet.arrayReduce.desc", "var arr = [1, 2, 3, 4, 5];\nvar sum = arr.reduce(function(acc, item) {\n    return acc + item;\n}, 0);\nconsole.log(sum); // 15"),
    ARRAY_SORT(Category.ARRAY, "snippet.arraySort.title", "snippet.arraySort.desc", "var arr = [3, 1, 4, 1, 5, 9, 2, 6];\n// Sort ascending\nvar sorted = arr.sort(function(a, b) {\n    return a - b;\n});\nconsole.log(sorted); // [1, 1, 2, 3, 4, 5, 6, 9]"),
    ARRAY_UNIQUE(Category.ARRAY, "snippet.arrayUnique.title", "snippet.arrayUnique.desc", "var arr = [1, 2, 2, 3, 3, 3, 4];\n// Remove duplicates\nvar unique = arr.filter(function(item, index, self) {\n    return self.indexOf(item) === index;\n});\nconsole.log(unique); // [1, 2, 3, 4]"),
    ARRAY_FLATTEN(Category.ARRAY, "snippet.arrayFlatten.title", "snippet.arrayFlatten.desc", "var arr = [[1, 2], [3, 4], [5]];\n// Flatten nested array\nvar flattened = arr.reduce(function(acc, item) {\n    return acc.concat(item);\n}, []);\nconsole.log(flattened); // [1, 2, 3, 4, 5]"),

    // Regular expressions
    REGEX_EXTRACT(Category.REGEX, "snippet.regexExtract.title", "snippet.regexExtract.desc", "var str = 'My email is test@example.com';\nvar regex = /[\\w._%+-]+@[\\w.-]+\\.[a-zA-Z]{2,4}/;\nvar email = str.match(regex)[0];\nconsole.log(email); // test@example.com"),

    // Calculation and encryption
    MD5(Category.ENCRYPT, "snippet.md5.title", "snippet.md5.desc", "var hash = MD5('Message').toString();\nconsole.log(hash);"),
    SHA256(Category.ENCRYPT, "snippet.sha256.title", "snippet.sha256.desc", "var hash = SHA256('Message').toString();\nconsole.log(hash);"),

    // CryptoJS 加密库
    CRYPTOJS_MD5(Category.CRYPTOJS, "snippet.cryptojsMd5.title", "snippet.cryptojsMd5.desc", "var hash = CryptoJS.MD5('message').toString();\nconsole.log('MD5:', hash);"),
    CRYPTOJS_SHA256(Category.CRYPTOJS, "snippet.cryptojsSha256.title", "snippet.cryptojsSha256.desc", "var hash = CryptoJS.SHA256('message').toString();\nconsole.log('SHA256:', hash);"),
    CRYPTOJS_AES_ENCRYPT(Category.CRYPTOJS, "snippet.cryptojsAesEncrypt.title", "snippet.cryptojsAesEncrypt.desc", "var encrypted = CryptoJS.AES.encrypt('sensitive data', 'secret key');\nvar encryptedStr = encrypted.toString();\nconsole.log('Encrypted:', encryptedStr);\npm.environment.set('encrypted', encryptedStr);"),
    CRYPTOJS_AES_DECRYPT(Category.CRYPTOJS, "snippet.cryptojsAesDecrypt.title", "snippet.cryptojsAesDecrypt.desc", "var encrypted = pm.environment.get('encrypted');\nvar decrypted = CryptoJS.AES.decrypt(encrypted, 'secret key');\nvar decryptedStr = decrypted.toString(CryptoJS.enc.Utf8);\nconsole.log('Decrypted:', decryptedStr);"),
    CRYPTOJS_HMAC(Category.CRYPTOJS, "snippet.cryptojsHmac.title", "snippet.cryptojsHmac.desc", "var message = 'data to sign';\nvar secret = pm.environment.get('api_secret');\nvar signature = CryptoJS.HmacSHA256(message, secret).toString();\npm.request.headers.add({key: 'X-Signature', value: signature});\nconsole.log('Signature:', signature);"),
    CRYPTOJS_BASE64(Category.CRYPTOJS, "snippet.cryptojsBase64.title", "snippet.cryptojsBase64.desc", "var text = 'Hello World';\nvar encoded = CryptoJS.enc.Base64.stringify(CryptoJS.enc.Utf8.parse(text));\nconsole.log('Base64 encoded:', encoded);\nvar decoded = CryptoJS.enc.Base64.parse(encoded).toString(CryptoJS.enc.Utf8);\nconsole.log('Decoded:', decoded);"),

    // Lodash 工具库
    LODASH_FILTER(Category.LODASH, "snippet.lodashFilter.title", "snippet.lodashFilter.desc", "var numbers = [1, 2, 3, 4, 5, 6];\nvar evens = _.filter(numbers, n => n % 2 === 0);\nconsole.log('Even numbers:', evens); // [2, 4, 6]"),
    LODASH_MAP(Category.LODASH, "snippet.lodashMap.title", "snippet.lodashMap.desc", "var numbers = [1, 2, 3];\nvar doubled = _.map(numbers, n => n * 2);\nconsole.log('Doubled:', doubled); // [2, 4, 6]"),
    LODASH_UNIQ(Category.LODASH, "snippet.lodashUniq.title", "snippet.lodashUniq.desc", "var numbers = [1, 2, 2, 3, 3, 3];\nvar unique = _.uniq(numbers);\nconsole.log('Unique:', unique); // [1, 2, 3]"),
    LODASH_PICK(Category.LODASH, "snippet.lodashPick.title", "snippet.lodashPick.desc", "var user = {id: 1, name: 'John', age: 30, email: 'john@example.com'};\nvar picked = _.pick(user, ['id', 'name']);\nconsole.log('Picked:', picked); // {id: 1, name: 'John'}"),
    LODASH_GROUPBY(Category.LODASH, "snippet.lodashGroupBy.title", "snippet.lodashGroupBy.desc", "var numbers = [6.1, 4.2, 6.3, 4.5];\nvar grouped = _.groupBy(numbers, Math.floor);\nconsole.log('Grouped:', grouped); // {4: [4.2, 4.5], 6: [6.1, 6.3]}"),
    LODASH_FIND(Category.LODASH, "snippet.lodashFind.title", "snippet.lodashFind.desc", "var users = [{id: 1, name: 'John'}, {id: 2, name: 'Jane'}];\nvar found = _.find(users, {id: 2});\nconsole.log('Found:', found); // {id: 2, name: 'Jane'}"),
    LODASH_SORTBY(Category.LODASH, "snippet.lodashSortBy.title", "snippet.lodashSortBy.desc", "var users = [{name: 'John', age: 30}, {name: 'Jane', age: 25}];\nvar sorted = _.sortBy(users, ['age', 'name']);\nconsole.log('Sorted:', sorted);"),

    // Moment 日期库
    MOMENT_NOW(Category.MOMENT, "snippet.momentNow.title", "snippet.momentNow.desc", "var now = moment().format('YYYY-MM-DD HH:mm:ss');\nconsole.log('Current time:', now);\npm.environment.set('timestamp', now);"),
    MOMENT_FORMAT(Category.MOMENT, "snippet.momentFormat.title", "snippet.momentFormat.desc", "var date = moment();\nconsole.log('ISO:', date.toISOString());\nconsole.log('Date:', date.format('YYYY-MM-DD'));\nconsole.log('Time:', date.format('HH:mm:ss'));\nconsole.log('Custom:', date.format('YYYY年MM月DD日'));"),
    MOMENT_ADD(Category.MOMENT, "snippet.momentAdd.title", "snippet.momentAdd.desc", "var tomorrow = moment().add(1, 'days').format('YYYY-MM-DD');\nvar nextWeek = moment().add(7, 'days').format('YYYY-MM-DD');\nconsole.log('Tomorrow:', tomorrow);\nconsole.log('Next week:', nextWeek);"),
    MOMENT_SUBTRACT(Category.MOMENT, "snippet.momentSubtract.title", "snippet.momentSubtract.desc", "var yesterday = moment().subtract(1, 'days').format('YYYY-MM-DD');\nvar lastMonth = moment().subtract(1, 'months').format('YYYY-MM-DD');\nconsole.log('Yesterday:', yesterday);\nconsole.log('Last month:', lastMonth);"),
    MOMENT_ISBEFORE(Category.MOMENT, "snippet.momentIsBefore.title", "snippet.momentIsBefore.desc", "var date1 = moment('2024-01-01');\nvar date2 = moment('2024-12-31');\nvar isBefore = date1.isBefore(date2);\nconsole.log('Is before:', isBefore); // true"),
    MOMENT_UNIX(Category.MOMENT, "snippet.momentUnix.title", "snippet.momentUnix.desc", "var timestamp = moment().unix();\nconsole.log('Unix timestamp:', timestamp);\npm.environment.set('timestamp', timestamp);"),

    // 完整示例
    EXAMPLE_API_SIGNATURE(Category.EXAMPLES, "snippet.exampleApiSignature.title", "snippet.exampleApiSignature.desc", "// 生成 API 签名\nvar requestId = uuid();\nvar timestamp = moment().unix();\nvar signData = {\n    requestId: requestId,\n    timestamp: timestamp,\n    method: pm.request.method,\n    path: pm.request.url.getPath()\n};\nvar signString = _.map(\n    _.sortBy(_.toPairs(signData), 0),\n    pair => pair[0] + '=' + pair[1]\n).join('&');\nvar signature = CryptoJS.HmacSHA256(signString, pm.environment.get('apiKey')).toString();\npm.request.headers.add({key: 'X-Signature', value: signature});\nconsole.log('API signature generated:', signature);"),
    EXAMPLE_VALIDATE_RESPONSE(Category.EXAMPLES, "snippet.exampleValidateResponse.title", "snippet.exampleValidateResponse.desc", "// 完整的响应验证\npm.test('响应验证', function() {\n    var jsonData = pm.response.json();\n    \n    // 验证必需字段\n    var requiredFields = ['code', 'message', 'data'];\n    var hasAllFields = _.every(requiredFields, field => _.has(jsonData, field));\n    pm.expect(hasAllFields).to.equal(true);\n    \n    // 验证字段类型\n    pm.expect(jsonData.code).to.be.a('number');\n    pm.expect(jsonData.message).to.be.a('string');\n    \n    console.log('✅ All validations passed');\n});"),

    // Cookie operations
    COOKIE_GET(Category.COOKIES, "snippet.cookieGet.title", "snippet.cookieGet.desc", "// Get cookie from response\nvar cookie = pm.cookies.get('JSESSIONID');\nif (cookie) {\n    console.log('Cookie name:', cookie.name);\n    console.log('Cookie value:', cookie.value);\n    console.log('Cookie domain:', cookie.domain);\n    console.log('Cookie path:', cookie.path);\n    // Save to environment\n    pm.environment.set('session_id', cookie.value);\n}"),
    COOKIE_GET_VALUE(Category.COOKIES, "snippet.cookieGetValue.title", "snippet.cookieGetValue.desc", "// Get cookie value directly (Postman style)\nvar sessionId = pm.cookies.get('JSESSIONID');\nif (sessionId) {\n    pm.environment.set('session_id', sessionId.value);\n    console.log('Session ID:', sessionId.value);\n} else {\n    console.log('Cookie not found');\n}"),
    COOKIE_HAS(Category.COOKIES, "snippet.cookieHas.title", "snippet.cookieHas.desc", "// Check if cookie exists\nif (pm.cookies.has('JSESSIONID')) {\n    console.log('Session cookie exists');\n    var cookie = pm.cookies.get('JSESSIONID');\n    pm.environment.set('session_id', cookie.value);\n} else {\n    console.log('Session cookie not found');\n}"),
    COOKIE_ALL(Category.COOKIES, "snippet.cookieAll.title", "snippet.cookieAll.desc", "// Get all response cookies\nvar allCookies = pm.cookies.getAll();\nconsole.log('Total cookies:', allCookies.length);\n\nallCookies.forEach(function(cookie) {\n    console.log('Cookie:', cookie.name + '=' + cookie.value);\n});"),
    COOKIE_POSTMAN_STYLE(Category.COOKIES, "snippet.cookiePostmanStyle.title", "snippet.cookiePostmanStyle.desc", "// Cookie helper syntax\nvar jsessionId = pm.getResponseCookie('JSESSIONID');\nif (jsessionId) {\n    pm.environment.set('session_id', jsessionId.value);\n    console.log('JSESSIONID:', jsessionId.value);\n}"),

    // Cookie Jar 操作 (设置 Cookie)
    COOKIE_JAR_SET(Category.COOKIES, "snippet.cookieJarSet.title", "snippet.cookieJarSet.desc", "// Set cookie using Cookie Jar\nvar jar = pm.cookies.jar();\n\n// Simple mode: set(url, name, value)\njar.set(pm.request.url, 'session_id', 'ABC123');\nconsole.log('Cookie set: session_id=ABC123');\n\n// Or with full options\njar.set(pm.request.url, {\n    name: 'auth_token',\n    value: pm.environment.get('token'),\n    domain: 'example.com',\n    path: '/',\n    secure: true,\n    httpOnly: true\n});\nconsole.log('Cookie set with options');"),
    COOKIE_JAR_GET(Category.COOKIES, "snippet.cookieJarGet.title", "snippet.cookieJarGet.desc", "// Get cookie using Cookie Jar\nvar jar = pm.cookies.jar();\n\njar.get(pm.request.url, 'session_id', function(error, cookie) {\n    if (error) {\n        console.log('Error getting cookie:', error);\n        return;\n    }\n    \n    if (cookie) {\n        console.log('Cookie found:', cookie.name + '=' + cookie.value);\n        pm.environment.set('session_id', cookie.value);\n    } else {\n        console.log('Cookie not found');\n    }\n});"),
    COOKIE_JAR_UNSET(Category.COOKIES, "snippet.cookieJarUnset.title", "snippet.cookieJarUnset.desc", "// Delete cookie using Cookie Jar\nvar jar = pm.cookies.jar();\n\n// Method 1: With callback\njar.unset(pm.request.url, 'session_id', function(error) {\n    if (error) {\n        console.log('❌ Error deleting cookie:', error);\n    } else {\n        console.log('✅ Cookie deleted: session_id');\n    }\n});\n\n// Method 2: Without callback (simpler)\njar.unset(pm.request.url, 'old_cookie');\nconsole.log('✅ Cookie deleted: old_cookie');"),
    COOKIE_JAR_CLEAR(Category.COOKIES, "snippet.cookieJarClear.title", "snippet.cookieJarClear.desc", "// Clear all cookies for current URL\nvar jar = pm.cookies.jar();\n\njar.clear(pm.request.url, function(error) {\n    if (error) {\n        console.log('Error clearing cookies:', error);\n    } else {\n        console.log('All cookies cleared for this domain');\n    }\n});"),
    COOKIE_JAR_GET_ALL(Category.COOKIES, "snippet.cookieJarGetAll.title", "snippet.cookieJarGetAll.desc", "// Get all cookies for current URL\nvar jar = pm.cookies.jar();\n\njar.getAll(pm.request.url, function(error, cookies) {\n    if (error) {\n        console.log('Error getting cookies:', error);\n        return;\n    }\n    \n    console.log('Total cookies:', cookies.length);\n    cookies.forEach(function(cookie) {\n        console.log('- ' + cookie.name + '=' + cookie.value);\n    });\n});"),
    COOKIE_SET_BEFORE_REQUEST(Category.COOKIES, "snippet.cookieSetBeforeRequest.title", "snippet.cookieSetBeforeRequest.desc", "// Set cookie before sending request\nvar jar = pm.cookies.jar();\nvar baseUrl = pm.request.url;\n\n// Set session cookie\nvar sessionId = pm.environment.get('session_id') || 'default_session';\njar.set(baseUrl, 'JSESSIONID', sessionId);\nconsole.log('Set session cookie:', sessionId);\n\n// Set authentication token\nvar token = pm.environment.get('auth_token');\nif (token) {\n    jar.set(baseUrl, 'auth_token', token);\n    console.log('Set auth token cookie');\n}"),

    // ===== 认证相关 (AUTHENTICATION) =====
    AUTH_BEARER_TOKEN(Category.AUTHENTICATION, "snippet.authBearerToken.title", "snippet.authBearerToken.desc", "// Bearer Token 认证\n// 约定：脚本里显式写入的 Authorization 优先于 auth tab 自动生成的 Authorization\nvar token = pm.environment.get('authToken');\n\nif (!token) {\n    console.log('❌ 未找到认证 Token');\n} else {\n    pm.request.headers.upsert({\n        key: 'Authorization',\n        value: 'Bearer ' + token\n    });\n    console.log('✅ Bearer Token 已添加');\n}"),

    AUTH_BASIC_AUTH(Category.AUTHENTICATION, "snippet.authBasicAuth.title", "snippet.authBasicAuth.desc", "// Basic Auth 认证\n// 约定：脚本里显式写入的 Authorization 优先于 auth tab 自动生成的 Authorization\nvar username = pm.environment.get('username') || 'admin';\nvar password = pm.environment.get('password') || 'password';\n\nvar credentials = CryptoJS.enc.Base64.stringify(\n    CryptoJS.enc.Utf8.parse(username + ':' + password)\n);\n\npm.request.headers.upsert({\n    key: 'Authorization',\n    value: 'Basic ' + credentials\n});\n\nconsole.log('✅ Basic Auth 已添加，用户:', username);"),

    AUTH_API_KEY(Category.AUTHENTICATION, "snippet.authApiKey.title", "snippet.authApiKey.desc", "// API Key 认证\nvar apiKey = pm.environment.get('apiKey');\n\nif (!apiKey) {\n    console.log('❌ 未找到 API Key');\n} else {\n    // 方式1: 请求头\n    pm.request.headers.upsert({\n        key: 'X-API-Key',\n        value: apiKey\n    });\n    \n    // 方式2: 查询参数 (根据需要选择)\n    // pm.request.params.add({\n    //     key: 'api_key',\n    //     value: apiKey\n    // });\n    \n    console.log('✅ API Key 已添加');\n}"),

    AUTH_HMAC_SIGNATURE(Category.AUTHENTICATION, "snippet.authHmacSignature.title", "snippet.authHmacSignature.desc", "// HMAC-SHA256 签名认证\nvar timestamp = Date.now().toString();\nvar method = pm.request.method;\nvar path = pm.request.url.getPath();\nvar secretKey = pm.environment.get('secretKey') || 'default-secret';\n\n// 构建签名字符串\nvar signString = method + '\\n' + path + '\\n' + timestamp;\nconsole.log('签名字符串:', signString);\n\n// 计算 HMAC-SHA256 签名\nvar signature = CryptoJS.HmacSHA256(signString, secretKey).toString();\n\n// 添加签名相关请求头\npm.request.headers.upsert({key: 'X-Timestamp', value: timestamp});\npm.request.headers.upsert({key: 'X-Signature', value: signature});\npm.request.headers.upsert({\n    key: 'X-App-Id',\n    value: pm.environment.get('appId') || 'default-app'\n});\n\nconsole.log('✅ 签名已生成:', signature.substring(0, 16) + '...');"),

    AUTH_JWT_PARSE(Category.AUTHENTICATION, "snippet.authJwtParse.title", "snippet.authJwtParse.desc", "// 解析 JWT Token\nvar token = pm.environment.get('jwt_token');\n\nif (!token) {\n    console.log('❌ 未找到 JWT Token');\n} else {\n    try {\n        // 分割 Token\n        var parts = token.split('.');\n        if (parts.length !== 3) {\n            throw new Error('Token 格式不正确');\n        }\n        \n        // 解码 payload 部分 (base64)\n        var payload = JSON.parse(atob(parts[1]));\n        console.log('✅ Token 解析成功');\n        console.log('Payload:', JSON.stringify(payload, null, 2));\n        \n        // 检查过期时间\n        if (payload.exp) {\n            var expireDate = new Date(payload.exp * 1000);\n            var now = new Date();\n            \n            if (now < expireDate) {\n                console.log('✅ Token 有效，过期时间:', expireDate.toLocaleString());\n            } else {\n                console.log('❌ Token 已过期');\n            }\n        }\n        \n        // 提取用户信息\n        if (payload.sub) pm.environment.set('userId', payload.sub);\n        if (payload.username) pm.environment.set('username', payload.username);\n        \n    } catch (error) {\n        console.log('❌ Token 解析失败:', error.message);\n    }\n}"),

    // ===== 性能测试 (PERFORMANCE) =====
    PERF_RESPONSE_TIME_CHECK(Category.PERFORMANCE, "snippet.perfResponseTimeCheck.title", "snippet.perfResponseTimeCheck.desc", "// 响应时间性能检查\nvar responseTime = pm.response.responseTime;\nvar threshold = parseInt(pm.environment.get('responseTimeThreshold')) || 1000;\n\npm.test('响应时间性能检查', function() {\n    pm.expect(responseTime).to.be.below(threshold);\n});\n\n// 性能等级评估\nvar grade = '';\nif (responseTime < threshold * 0.3) {\n    grade = 'A+ 优秀';\n} else if (responseTime < threshold * 0.5) {\n    grade = 'A 良好';\n} else if (responseTime < threshold * 0.8) {\n    grade = 'B 一般';\n} else if (responseTime < threshold) {\n    grade = 'C 及格';\n} else {\n    grade = 'D 较慢';\n}\n\nconsole.log('⏱️  响应时间:', responseTime, 'ms');\nconsole.log('📊 性能等级:', grade);\nconsole.log('🎯 性能基准:', threshold, 'ms');"),

    PERF_RESPONSE_SIZE_CHECK(Category.PERFORMANCE, "snippet.perfResponseSizeCheck.title", "snippet.perfResponseSizeCheck.desc", "// 响应大小检查\nvar size = pm.response.size();\n\nconsole.log('📦 响应大小统计:');\nconsole.log('  响应体:', size.body, 'bytes');\nconsole.log('  响应头:', size.header, 'bytes');\nconsole.log('  总大小:', size.total, 'bytes');\n\n// 大小断言 (默认10MB)\nvar maxSize = parseInt(pm.environment.get('maxResponseSize')) || 10485760;\n\npm.test('响应大小合理', function() {\n    pm.expect(size.total).to.be.below(maxSize);\n});\n\nif (size.total > maxSize * 0.8) {\n    console.log('⚠️  响应体较大，接近限制');\n}"),

    PERF_STATISTICS(Category.PERFORMANCE, "snippet.perfStatistics.title", "snippet.perfStatistics.desc", "// 性能统计与平均值计算\nvar responseTime = pm.response.responseTime;\nvar endpoint = pm.request.url.getPath();\n\n// 获取历史数据\nvar totalTime = parseFloat(pm.environment.get('totalResponseTime')) || 0;\nvar requestCount = parseInt(pm.environment.get('requestCount')) || 0;\n\n// 累加\ntotalTime += responseTime;\nrequestCount += 1;\n\n// 保存\npm.environment.set('totalResponseTime', totalTime.toString());\npm.environment.set('requestCount', requestCount.toString());\n\n// 计算平均值\nvar avgTime = totalTime / requestCount;\n\nconsole.log('=== 性能统计 ===');\nconsole.log('本次响应:', responseTime, 'ms');\nconsole.log('平均响应:', avgTime.toFixed(2), 'ms');\nconsole.log('请求总数:', requestCount);\nconsole.log('总耗时:', totalTime.toFixed(2), 'ms');"),

    // ===== 数据验证 (VALIDATION) =====
    VALIDATE_REQUIRED_FIELDS(Category.VALIDATION, "snippet.validateRequiredFields.title", "snippet.validateRequiredFields.desc", "// 验证必填字段\npm.test('必填字段验证', function() {\n    var jsonData = pm.response.json();\n    var requiredFields = ['code', 'message', 'data'];\n    var errors = [];\n    \n    requiredFields.forEach(function(field) {\n        if (!jsonData.hasOwnProperty(field)) {\n            errors.push('缺少字段: ' + field);\n        } else if (jsonData[field] === null || jsonData[field] === undefined) {\n            errors.push('字段为空: ' + field);\n        }\n    });\n    \n    if (errors.length > 0) {\n        console.log('❌ 验证失败:');\n        errors.forEach(function(err) {\n            console.log('  -', err);\n        });\n        throw new Error(errors.join('; '));\n    } else {\n        console.log('✅ 所有必填字段验证通过');\n    }\n});"),

    VALIDATE_DATA_TYPES(Category.VALIDATION, "snippet.validateDataTypes.title", "snippet.validateDataTypes.desc", "// 数据类型验证\npm.test('数据类型验证', function() {\n    var jsonData = pm.response.json();\n    var schema = {\n        code: 'number',\n        message: 'string',\n        data: 'object',\n        success: 'boolean',\n        timestamp: 'number'\n    };\n    \n    var errors = [];\n    \n    for (var key in schema) {\n        if (jsonData.hasOwnProperty(key)) {\n            var expectedType = schema[key];\n            var actualType = typeof jsonData[key];\n            \n            if (actualType !== expectedType) {\n                errors.push(\n                    '字段 ' + key + ' 类型错误: ' +\n                    '期望 ' + expectedType + ', 实际 ' + actualType\n                );\n            }\n        }\n    }\n    \n    pm.expect(errors).to.have.lengthOf(0);\n    \n    if (errors.length === 0) {\n        console.log('✅ 所有字段类型验证通过');\n    }\n});"),

    VALIDATE_BUSINESS_LOGIC(Category.VALIDATION, "snippet.validateBusinessLogic.title", "snippet.validateBusinessLogic.desc", "// 业务逻辑验证\npm.test('订单数据一致性验证', function() {\n    var jsonData = pm.response.json();\n    var order = jsonData.data.order;\n    \n    // 1. 金额计算验证\n    var calculatedSubtotal = 0;\n    order.items.forEach(function(item) {\n        calculatedSubtotal += item.price * item.quantity;\n    });\n    pm.expect(Math.round(calculatedSubtotal * 100) / 100).to.equal(order.subtotal);\n    console.log('✅ 小计金额验证通过:', order.subtotal);\n    \n    // 2. 总金额验证\n    var calculatedTotal = order.subtotal + (order.shippingFee || 0) - (order.discount || 0);\n    calculatedTotal = Math.round(calculatedTotal * 100) / 100;\n    pm.expect(calculatedTotal).to.equal(order.totalAmount);\n    console.log('✅ 总金额验证通过:', order.totalAmount);\n    \n    // 3. 商品数量验证\n    pm.expect(order.items.length).to.be.above(0);\n    console.log('✅ 商品数量验证通过:', order.items.length);\n});"),

    VALIDATE_ENUM_VALUES(Category.VALIDATION, "snippet.validateEnumValues.title", "snippet.validateEnumValues.desc", "// 枚举值验证\npm.test('枚举值验证', function() {\n    var jsonData = pm.response.json();\n    \n    // 定义允许的枚举值\n    var allowedStatuses = ['pending', 'processing', 'completed', 'cancelled'];\n    var allowedRoles = ['admin', 'user', 'guest'];\n    \n    // 验证状态值\n    if (jsonData.status) {\n        pm.expect(allowedStatuses).to.include(jsonData.status);\n        console.log('✅ 状态值有效:', jsonData.status);\n    }\n    \n    // 验证角色值\n    if (jsonData.user && jsonData.user.role) {\n        pm.expect(allowedRoles).to.include(jsonData.user.role);\n        console.log('✅ 角色值有效:', jsonData.user.role);\n    }\n});"),

    // ===== 数据处理 (DATA_PROCESSING) =====
    DATA_EXTRACT_NESTED(Category.DATA_PROCESSING, "snippet.dataExtractNested.title", "snippet.dataExtractNested.desc", "// 提取嵌套数据 (使用 Lodash)\nvar jsonData = pm.response.json();\n\n// 安全提取嵌套属性\nvar userId = _.get(jsonData, 'data.user.id');\nvar userName = _.get(jsonData, 'data.user.profile.name');\nvar firstEmail = _.get(jsonData, 'data.user.emails[0]');\nvar address = _.get(jsonData, 'data.user.profile.address.city', 'Unknown');\n\n// 保存到环境变量\nif (userId) pm.environment.set('userId', userId);\nif (userName) pm.environment.set('userName', userName);\nif (firstEmail) pm.environment.set('userEmail', firstEmail);\n\nconsole.log('✅ 数据提取完成:');\nconsole.log('  User ID:', userId);\nconsole.log('  User Name:', userName);\nconsole.log('  Email:', firstEmail);\nconsole.log('  City:', address);"),

    DATA_TRANSFORM_ARRAY(Category.DATA_PROCESSING, "snippet.dataTransformArray.title", "snippet.dataTransformArray.desc", "// 数组数据转换 (使用 Lodash)\nvar jsonData = pm.response.json();\nvar items = jsonData.data.items || [];\n\n// 提取所有 ID\nvar ids = _.map(items, 'id');\npm.environment.set('itemIds', JSON.stringify(ids));\nconsole.log('✅ 提取了', ids.length, '个 ID:', ids);\n\n// 过滤活跃项\nvar activeItems = _.filter(items, {status: 'active'});\nconsole.log('✅ 活跃项数:', activeItems.length);\n\n// 按分类分组\nvar groupedByCategory = _.groupBy(items, 'category');\nconsole.log('✅ 分组结果:', Object.keys(groupedByCategory));\n\n// 计算总价\nvar totalPrice = _.sumBy(items, function(item) {\n    return item.price * item.quantity;\n});\nconsole.log('✅ 总价:', totalPrice.toFixed(2));"),

    DATA_FILTER_AND_SORT(Category.DATA_PROCESSING, "snippet.dataFilterAndSort.title", "snippet.dataFilterAndSort.desc", "// 数据过滤和排序 (使用 Lodash)\nvar jsonData = pm.response.json();\nvar users = jsonData.data.users || [];\n\n// 过滤年龄大于25的用户\nvar filteredUsers = _.filter(users, function(user) {\n    return user.age > 25;\n});\nconsole.log('✅ 过滤后用户数:', filteredUsers.length);\n\n// 按年龄和姓名排序\nvar sortedUsers = _.sortBy(filteredUsers, ['age', 'name']);\n\n// 提取特定字段\nvar simplified = _.map(sortedUsers, function(user) {\n    return _.pick(user, ['id', 'name', 'age', 'email']);\n});\n\nconsole.log('✅ 处理后的数据:');\nsimplified.forEach(function(user, index) {\n    console.log((index + 1) + '.', user.name, '(' + user.age + '岁)');\n});\n\n// 保存处理后的数据\npm.environment.set('processedUsers', JSON.stringify(simplified));"),

    DATA_MERGE_OBJECTS(Category.DATA_PROCESSING, "snippet.dataMergeObjects.title", "snippet.dataMergeObjects.desc", "// 合并多个对象 (使用 Lodash)\nvar jsonData = pm.response.json();\nvar baseData = jsonData.data || {};\n\n// 默认配置\nvar defaults = {\n    timeout: 5000,\n    retries: 3,\n    debug: false,\n    pageSize: 20\n};\n\n// 合并配置 (深度合并)\nvar config = _.merge({}, defaults, baseData.config || {});\n\nconsole.log('✅ 合并后的配置:');\nconsole.log(JSON.stringify(config, null, 2));\n\n// 保存配置\npm.environment.set('apiConfig', JSON.stringify(config));"),

    // ===== 请求修改 (REQUEST_MODIFICATION) =====
    REQ_DYNAMIC_HEADERS(Category.REQUEST_MODIFICATION, "snippet.reqDynamicHeaders.title", "snippet.reqDynamicHeaders.desc", "// 批量添加动态请求头\nvar timestamp = moment().valueOf();\nvar requestId = pm.uuid();\n\nvar headers = [\n    {key: 'X-Request-ID', value: requestId},\n    {key: 'X-Timestamp', value: timestamp.toString()},\n    {key: 'X-Client-Version', value: '1.0.0'},\n    {key: 'X-Platform', value: 'web'},\n    {key: 'X-Device-ID', value: pm.environment.get('deviceId') || pm.uuid()}\n];\n\nheaders.forEach(function(header) {\n    pm.request.headers.upsert(header);\n});\n\nconsole.log('✅ 已添加', headers.length, '个动态请求头');"),

    REQ_DYNAMIC_PARAMS(Category.REQUEST_MODIFICATION, "snippet.reqDynamicParams.title", "snippet.reqDynamicParams.desc", "// 批量添加动态查询参数\nvar commonParams = [\n    {key: 'timestamp', value: Date.now().toString()},\n    {key: 'appId', value: pm.environment.get('appId') || 'default'},\n    {key: 'lang', value: 'zh-CN'},\n    {key: 'timezone', value: 'Asia/Shanghai'},\n    {key: 'platform', value: 'web'}\n];\n\ncommonParams.forEach(function(param) {\n    pm.request.params.add(param);\n});\n\nconsole.log('✅ 已添加', commonParams.length, '个查询参数');"),

    REQ_CONDITIONAL_MODIFY(Category.REQUEST_MODIFICATION, "snippet.reqConditionalModify.title", "snippet.reqConditionalModify.desc", "// 根据环境条件修改请求\nvar env = pm.environment.get('environment') || 'dev';\n\n// 环境配置\nvar configs = {\n    dev: {\n        baseUrl: 'https://dev-api.example.com',\n        timeout: 10000,\n        debug: true\n    },\n    test: {\n        baseUrl: 'https://test-api.example.com',\n        timeout: 8000,\n        debug: true\n    },\n    prod: {\n        baseUrl: 'https://api.example.com',\n        timeout: 5000,\n        debug: false\n    }\n};\n\nvar config = configs[env];\nif (!config) {\n    console.log('❌ 未知环境:', env);\n} else {\n    pm.environment.set('baseUrl', config.baseUrl);\n    pm.environment.set('timeout', config.timeout.toString());\n    \n    pm.request.headers.upsert({\n        key: 'X-Environment',\n        value: env\n    });\n    \n    console.log('✅ 已切换到', env, '环境');\n    console.log('  Base URL:', config.baseUrl);\n}"),

    // ===== 完整示例 (EXAMPLES) - 补充更多 =====
    EXAMPLE_LOGIN_FLOW(Category.EXAMPLES, "snippet.exampleLoginFlow.title", "snippet.exampleLoginFlow.desc", "// 完整的登录流程处理\npm.test('登录流程验证', function() {\n    // 1. 状态码验证\n    pm.response.to.have.status(200);\n    \n    // 2. 解析响应\n    var jsonData = pm.response.json();\n    \n    // 3. 业务验证\n    pm.expect(jsonData).to.have.property('code');\n    pm.expect(jsonData.code).to.equal(200);\n    pm.expect(jsonData.data).to.have.property('token');\n    pm.expect(jsonData.data).to.have.property('refreshToken');\n    \n    // 4. Token 格式验证 (JWT)\n    var tokenPattern = /^[A-Za-z0-9\\-_]+\\.[A-Za-z0-9\\-_]+\\.[A-Za-z0-9\\-_]+$/;\n    pm.expect(jsonData.data.token).to.match(tokenPattern);\n    \n    // 5. 保存认证信息\n    pm.environment.set('authToken', jsonData.data.token);\n    pm.environment.set('refreshToken', jsonData.data.refreshToken);\n    pm.environment.set('userId', jsonData.data.userInfo.userId);\n    pm.environment.set('username', jsonData.data.userInfo.username);\n    \n    // 6. 设置过期时间\n    if (jsonData.data.expiresIn) {\n        var expireTime = Date.now() + (jsonData.data.expiresIn * 1000);\n        pm.environment.set('tokenExpireTime', expireTime.toString());\n    }\n    \n    console.log('✅ 登录成功');\n    console.log('  用户:', jsonData.data.userInfo.username);\n    console.log('  Token 已保存');\n});"),
    EXAMPLE_ITERATION_DATA(Category.EXAMPLES, "snippet.exampleIterationData.title", "snippet.exampleIterationData.desc", "// 数据驱动请求示例\n// 假设 CSV 表头为: userId, token, expectedStatus\n// 在请求中可直接使用:\n//   URL:    https://example.com/users/{{userId}}\n//   Header: Authorization: Bearer {{token}}\n//   Body:   {\"userId\":\"{{userId}}\"}\n\nvar userId = pm.iterationData.get('userId');\nvar token = pm.iterationData.get('token');\nvar expectedStatus = parseInt(pm.iterationData.get('expectedStatus') || '200', 10);\n\npm.request.headers.upsert({\n    key: 'X-Data-User',\n    value: userId || ''\n});\n\npm.test('CSV 行数据已注入', function () {\n    pm.expect(userId).to.not.eql(null);\n    pm.expect(token).to.not.eql(null);\n});\n\npm.variables.set('expectedStatus', String(expectedStatus));\n\nconsole.log('当前 userId =', userId);\nconsole.log('当前 expectedStatus =', expectedStatus);"),
    EXAMPLE_LOCAL_REQUIRE(Category.EXAMPLES, "snippet.exampleLocalRequire.title", "snippet.exampleLocalRequire.desc", "// 本地 require() 测试\n// 该示例假设当前工作区就是仓库根目录。\n// local-parent.js 内部还会继续 require('./local-child.js')。\nvar localDemo = require('./docs/examples/js-require/local-parent.js');\nvar localResult = localDemo.describe('easy-postman');\n\nconsole.log('local require result:', localResult);\nconsole.log('local require marker:', localDemo.marker());\npm.variables.set('localRequireResult', localResult);\n"),
    EXAMPLE_REMOTE_REQUIRE(Category.EXAMPLES, "snippet.exampleRemoteRequire.title", "snippet.exampleRemoteRequire.desc", "// 远程 require() 测试\n// 使用前请先到“设置 -> 请求设置 -> 脚本加载”开启“允许从网络加载脚本”。\nvar dayjs = require('https://cdn.jsdelivr.net/npm/dayjs@1.11.13/dayjs.min.js');\nvar remoteResult = dayjs('2026-03-27').add(1, 'day').format('YYYY-MM-DD');\n\nconsole.log('remote require result:', remoteResult);\npm.variables.set('remoteRequireResult', remoteResult);\n"),

    EXAMPLE_PAGINATION(Category.EXAMPLES, "snippet.examplePagination.title", "snippet.examplePagination.desc", "// 分页数据处理完整示例\nvar jsonData = pm.response.json();\n\npm.test('分页数据验证', function() {\n    // 验证分页结构\n    pm.expect(jsonData.data).to.have.property('list');\n    pm.expect(jsonData.data).to.have.property('total');\n    pm.expect(jsonData.data).to.have.property('pageNum');\n    pm.expect(jsonData.data).to.have.property('pageSize');\n    \n    // 验证数据类型\n    pm.expect(Array.isArray(jsonData.data.list)).to.equal(true);\n    pm.expect(jsonData.data.total).to.be.a('number');\n    \n    // 验证逻辑合理性\n    var listLength = jsonData.data.list.length;\n    var pageSize = jsonData.data.pageSize;\n    pm.expect(listLength).to.be.below(pageSize + 1);\n    \n    console.log('✅ 分页验证通过');\n    console.log('  当前页:', jsonData.data.pageNum);\n    console.log('  每页数量:', pageSize);\n    console.log('  当前页记录:', listLength);\n    console.log('  总记录数:', jsonData.data.total);\n    \n    // 计算分页信息\n    var totalPages = Math.ceil(jsonData.data.total / pageSize);\n    var hasMore = jsonData.data.pageNum < totalPages;\n    \n    console.log('  总页数:', totalPages);\n    console.log('  还有更多:', hasMore);\n    \n    // 保存用于下一页请求\n    if (hasMore) {\n        var nextPage = jsonData.data.pageNum + 1;\n        pm.environment.set('nextPageNum', nextPage.toString());\n        console.log('  ➡️  下一页:', nextPage);\n    }\n});"),

    EXAMPLE_ES_ASSERT(Category.EXAMPLES, "snippet.exampleEsAssert.title", "snippet.exampleEsAssert.desc", "// Elasticsearch 查询 + 断言\nvar esResp = pm.elasticsearch.request({\n    baseUrl: pm.environment.get('esBaseUrl') || 'http://localhost:9200',\n    username: pm.environment.get('esUser') || '',\n    password: pm.environment.get('esPassword') || '',\n    method: 'GET',\n    path: '/' + (pm.environment.get('esIndex') || 'orders') + '/_search',\n    body: JSON.stringify({\n        query: { match_all: {} },\n        size: 1\n    })\n});\n\npm.test('Elasticsearch query success', function () {\n    pm.expect(esResp.code).to.equal(200);\n});\n\nif (esResp.json && esResp.json.hits && esResp.json.hits.total) {\n    console.log('ES total hits:', esResp.json.hits.total);\n}"),
    EXAMPLE_ES_WRITE_ASSERT(Category.EXAMPLES, "snippet.exampleEsWriteAssert.title", "snippet.exampleEsWriteAssert.desc", "// Elasticsearch 写入 + 断言\nvar esIndex = pm.environment.get('esIndex') || 'orders';\nvar docId = pm.environment.get('esDocId') || 'order-1001';\nvar esWriteResp = pm.elasticsearch.request({\n    baseUrl: pm.environment.get('esBaseUrl') || 'http://localhost:9200',\n    username: pm.environment.get('esUser') || '',\n    password: pm.environment.get('esPassword') || '',\n    method: 'POST',\n    path: '/' + esIndex + '/_doc/' + docId,\n    body: JSON.stringify({ orderId: 1001, status: 'CREATED', source: 'easy-postman' })\n});\n\npm.test('Elasticsearch write success', function () {\n    pm.expect(esWriteResp.code).to.be.within(200, 201);\n});\n\nconsole.log('Elasticsearch write response:', esWriteResp.body);"),
    EXAMPLE_INFLUX_QUERY_ASSERT(Category.EXAMPLES, "snippet.exampleInfluxQueryAssert.title", "snippet.exampleInfluxQueryAssert.desc", "// InfluxDB v1 查询 + 断言\nvar influxResp = pm.influxdb.query({\n    baseUrl: pm.environment.get('influxBaseUrl') || 'http://localhost:8086',\n    version: 'v1',\n    db: pm.environment.get('influxDb') || 'metrics',\n    username: pm.environment.get('influxUser') || 'root',\n    password: pm.environment.get('influxPassword') || 'root',\n    query: 'SELECT * FROM cpu ORDER BY time DESC LIMIT 1'\n});\n\npm.test('Influx query success', function () {\n    pm.expect(influxResp.code).to.equal(200);\n    pm.expect(influxResp.json).to.exist();\n});\n\nconsole.log('Influx query response:', influxResp.body);"),
    EXAMPLE_INFLUX_WRITE_ASSERT(Category.EXAMPLES, "snippet.exampleInfluxWriteAssert.title", "snippet.exampleInfluxWriteAssert.desc", "// InfluxDB v1 写入 + 断言\nvar influxWriteResp = pm.influxdb.write({\n    baseUrl: pm.environment.get('influxBaseUrl') || 'http://localhost:8086',\n    version: 'v1',\n    db: pm.environment.get('influxDb') || 'metrics',\n    username: pm.environment.get('influxUser') || 'root',\n    password: pm.environment.get('influxPassword') || 'root',\n    precision: 'ms',\n    lineProtocol: 'api_requests,service=order count=1i ' + Date.now()\n});\n\npm.test('Influx write success', function () {\n    pm.expect(influxWriteResp.code).to.equal(204);\n});\n\nconsole.log('Influx write meta:', JSON.stringify(influxWriteResp.meta));");

    public final Category type;
    public final String titleKey;
    public final String descKey;
    public final String code;

    SnippetType(Category type, String titleKey, String descKey, String code) {
        this.type = type;
        this.titleKey = titleKey;
        this.descKey = descKey;
        this.code = code;
    }
}
