package com.laker.postman.plugin.capture;

enum CaptureDiagnosticPhase {
    SOURCE_RESOLVE,
    INBOUND_ACCEPT,
    HTTP_REQUEST,
    CONNECT,
    FILTER_DECISION,
    BYPASS_TUNNEL,
    MITM_CERT,
    CONNECT_ACK,
    CLIENT_TLS,
    DECRYPTED_HTTP,
    TARGET_CONNECT,
    TARGET_TLS,
    TARGET_REQUEST,
    TARGET_RESPONSE,
    CLIENT_RESPONSE,
    WEBSOCKET_UPGRADE,
    WEBSOCKET_FRAME,
    FLOW_COMPLETE,
    FLOW_FAILED,
    CLIENT_CLOSED,
    TARGET_CLOSED
}
