package com.laker.postman.http.runtime.observation;

/**
 * HTTP 执行层产出的网络日志阶段。
 * <p>
 * 这里只保留传输语义，不携带颜色、图标等 Swing 展示信息；UI 层负责把这些阶段映射成具体样式。
 */
public enum NetworkLogEventStage {
    FAILED,
    CALL_FAILED,
    REQUEST_FAILED,
    RESPONSE_FAILED,
    CONNECT_FAILED,
    CANCELED,
    CALL_START,
    CALL_END,
    DISPATCHER_QUEUE_START,
    DISPATCHER_QUEUE_END,
    RETRY_DECISION,
    FOLLOW_UP_DECISION,
    CACHE_HIT,
    CACHE_MISS,
    CACHE_CONDITIONAL_HIT,
    SATISFACTION_FAILURE,
    REQUEST_PREPARED,
    SECURE_CONNECT_START,
    SECURE_CONNECT_END,
    CONNECT_START,
    CONNECT_END,
    CONNECTION_ACQUIRED,
    CONNECTION_RELEASED,
    DNS_START,
    DNS_END,
    PROXY_SELECT,
    PROXY_SELECT_START,
    PROXY_SELECT_END,
    REQUEST_HEADERS_START,
    REQUEST_HEADERS_END,
    REQUEST_BODY_START,
    REQUEST_BODY_END,
    RESPONSE_HEADERS_START,
    RESPONSE_HEADERS_END,
    RESPONSE_HEADERS_END_REDIRECT,
    RESPONSE_BODY_START,
    RESPONSE_BODY_END,
    REDIRECT,
    DEFAULT
}
